### ISSUE TITLE
Feature Request: option to install other dependencies

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/tpot-feedstock#19]
Following https://github.com/EpistasisLab/tpot/issues/1005#issuecomment-575860780 it was suggested that an option for installing tpot with other dependencies could be a conda-forge install called tpot-full. This would get additional optional packages and would be smarter with version pinning/testing than a blanket install command (https://github.com/EpistasisLab/tpot/pull/1006/files)

**Comment by bollwyvl** [comment]
on it...
